name: Cache Configuration

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        type: string
        default: '20'
      cache-version:
        description: 'Cache version for invalidation'
        required: false
        type: string
        default: 'v3'

jobs:
  cache-setup:
    name: Setup Cache
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Generate cache key
        id: cache-key
        run: |
          KEY="${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.json') }}-${{ inputs.cache-version }}"
          echo "key=$KEY" >> $GITHUB_OUTPUT
          echo "Generated cache key: $KEY"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .next/cache
            .next/static
            .next/standalone
            .eslintcache
            .tsbuildinfo
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ inputs.cache-version }}
            ${{ runner.os }}-${{ inputs.node-version }}-${{ inputs.cache-version }}
            ${{ runner.os }}-${{ inputs.node-version }}-
